### ISSUE TITLE
Failed to install emnity

### ISSUE THREAD

**Issue by popmanbrad** [enmity-mod/tweak#39]
whenever i try to install an updated version of emnity altstore and sideloadly give me the same error of "the filename or extension is too long" so i cant install it

**Comment by sfksuperman** [comment]
create_directories: The filename or extension is too long.: "C:\Users\xyz\AppData\Local\Temp\654ace7d-17de-4e24-8mb0-658e9371054a\Payload\App.app\assets\_node_modules\.pnpm\@react-navigation+elements@1.3.18_patch_hash=tm3j4nw5qxof2dxeh46s5mokpa_@react-navigation+nat_eqnm6ustzf2c5ljdvmfr6cc724\node_modules\"

**Comment by sfksuperman** [comment]
Is there anyone who cares about this app or not?

**Comment by policias** [comment]
Same Issue

**Comment by policias** [comment]
Fixed: Join to their Discord server (discord.gg/enmity) and go to the support channel, there you can find the fixed .ipa file.

**Comment by sfksuperman** [comment]
> Fixed: Join to their Discord server (discord.gg/enmity) and go to the support channel, there you can find the fixed .ipa file.

I tried the fixed ipa file but the app was not working properly. It was only opening and showing a progress circle. I talked there in a group and they shared me on .js file but that didn't solve the issue.
Still, it's broken.

**Comment by marioparaschiv** [comment]
This issue was fixed in more recent Enmity IPAs.
